import * as z from 'zod';

export const JOBCARDS: JobCard[] = [
  {
    id: 1,
    jobcardNo: '12345',
    client: 'Test Client 1',
    description: '2 no 3 seater sofa',
    cumulativeHrs: 120,
    hoursInProduction: 56,
    currentDepartment: 'joinery',
    startedOn: new Date('2023-08-12'),
    status: 'ongoing',
    salesPerson: 'Eunice',
  },
  {
    id: 2,
    jobcardNo: '12346',
    client: 'Test Client 2',
    description: '1 no. console mirror with wrought iron features',
    cumulativeHrs: 156,
    hoursInProduction: 24,
    currentDepartment: 'machinery',
    startedOn: new Date('2023-08-16'),
    status: 'ongoing',
    salesPerson: 'Donna',
  },
  {
    id: 3,
    jobcardNo: '12347',
    client: 'Test Client 2',
    description: '2 no winta bedside cabinets',
    cumulativeHrs: 88,
    hoursInProduction: 72,
    currentDepartment: 'upholstery',
    startedOn: new Date('2023-08-16'),
    status: 'paused',
    salesPerson: 'Julie',
  },
  {
    id: 4,
    jobcardNo: '12348',
    client: 'Test Client 3',
    description: '1 no. shinda foot rest',
    cumulativeHrs: 120,
    hoursInProduction: 130,
    currentDepartment: 'finishing',
    startedOn: new Date('2023-08-10'),
    status: 'completed',
    completedDate: new Date('2023-08-24'),
    salesPerson: 'Moni',
  },
  {
    id: 5,
    jobcardNo: '12349',
    client: 'Test Client 4',
    description: '2 no. armchairs',
    cumulativeHrs: 96,
    hoursInProduction: 33,
    currentDepartment: 'carving',
    startedOn: new Date('2023-08-29'),
    status: 'ongoing',
    salesPerson: 'Vir',
  },
  {
    id: 6,
    jobcardNo: '12350',
    client: 'Test Client 5',
    description: '1 no ottoman',
    cumulativeHrs: 144,
    hoursInProduction: 60,
    currentDepartment: 'sanding',
    startedOn: new Date('2023-08-24'),
    status: 'ongoing',
    salesPerson: 'Eunice',
  },
  {
    id: 7,
    jobcardNo: '12351',
    client: 'Test Client 1',
    description: '1 no. 3 seater sofa',
    cumulativeHrs: 124,
    hoursInProduction: 120,
    currentDepartment: 'finishing',
    startedOn: new Date('2023-08-30'),
    status: 'ongoing',
    salesPerson: 'Donna',
  },
  {
    id: 8,
    jobcardNo: '12352',
    client: 'Test Client 7',
    description: '1 no. study desk',
    cumulativeHrs: 160,
    hoursInProduction: 56,
    currentDepartment: 'joinery',
    startedOn: new Date('2023-08-30'),
    status: 'ongoing',
    salesPerson: 'Julie',
  },
  {
    id: 9,
    jobcardNo: '12353',
    client: 'Test Client 10',
    description: '1 no. chaise lounge',
    cumulativeHrs: 144,
    hoursInProduction: 72,
    currentDepartment: 'polishing',
    startedOn: new Date('2023-08-23'),
    status: 'paused',
    salesPerson: 'Moni',
  },
  {
    id: 10,
    jobcardNo: '12354',
    client: 'Test Client 4',
    description: '1 no. bespoke office desk',
    cumulativeHrs: 200,
    hoursInProduction: 12,
    currentDepartment: 'yard',
    startedOn: new Date('2023-09-12'),
    status: 'ongoing',
    salesPerson: 'Vir',
  },
  {
    id: 11,
    jobcardNo: '12355',
    client: 'Test Client 4',
    description: 'quarter round (windows)',
    cumulativeHrs: 56,
    hoursInProduction: 48,
    currentDepartment: 'finishing',
    startedOn: new Date('2023-09-01'),
    status: 'completed',
    completedDate: new Date('2023-09-14'),
    salesPerson: 'Eunice',
  },
  {
    id: 12,
    jobcardNo: '12356',
    client: 'Panesar',
    description: '1 no. coffee table',
    cumulativeHrs: 120,
    hoursInProduction: 88,
    currentDepartment: 'sanding',
    startedOn: new Date('2023-09-01'),
    status: 'ongoing',
    salesPerson: 'Donna',
  },
  {
    id: 13,
    jobcardNo: '12357',
    client: 'Test Client 2',
    description: 'wine cellar',
    cumulativeHrs: 62,
    hoursInProduction: 64,
    currentDepartment: 'finishing',
    startedOn: new Date('2023-09-06'),
    status: 'completed',
    completedDate: new Date('2023-09-13'),
    salesPerson: 'Julie',
  },
  {
    id: 14,
    jobcardNo: '12358',
    client: 'Test Client 2',
    description: '4 no. chest of drawers',
    cumulativeHrs: 96,
    hoursInProduction: 48,
    currentDepartment: 'carving',
    startedOn: new Date('2023-09-06'),
    status: 'completed',
    salesPerson: 'Vir',
  },
];

export const formSchema = z.object({
  jobcardNo: z
    .string()
    .nonempty('Field is required')
    .length(5, 'Invalid Job Card No'),
  description: z.string().nonempty('Field is required'),
  client: z.string().nonempty('Field is required'),
  salesPerson: z.string().nonempty('Field is required'),
  startDate: z.date({ required_error: 'Field is required' }),
  yardHrs: z.number().min(1, 'Cannot be less than 1').optional(),
  machineryHrs: z.number().min(1, 'Cannot be less than 1').optional(),
  joineryHrs: z.number().min(1, 'Cannot be less than 1').optional(),
  carvingHrs: z.number().min(1, 'Cannot be less than 1').optional(),
  sandingHrs: z.number().min(1, 'Cannot be less than 1').optional(),
  polishingHrs: z.number().min(1, 'Cannot be less than 1').optional(),
  upholsteryHrs: z.number().min(1, 'Cannot be less than 1').optional(),
  finishingHrs: z.number().min(1, 'Cannot be less than 1').optional(),
  cncHrs: z.number().min(1, 'Cannot be less than 1').optional(),
});
